# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kazuhiro.github.io
email: jarzemski.piotr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It is all about how to mine the best quality code. No matter, if it is Scala, Clojure, Java, Go, or something else.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kazuhiro.github.com" # the base hostname & protocol for your site
twitter_username: kh1ramatsu
github_username:  kazuhiro
linkedin_username: piotrjarzemski

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
